server:
  port: 8080
  servlet:
    context-path: /store

logging:
  level:
    root: DEBUG

external:
  servicekey: HBL%2FY0u39MG3pXAvaoRngGVc96fOUxmYD2aLu6L0MCCZjDure7gOD2e1ikw0kjRkPg%2F2pu9J0znei3JR1Geq3g%3D%3D
  host: http://apis.data.go.kr/B553077/api/open/sdsc

--- # production
spring:
  profiles: prod
  #application:
    #basePath: /
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:mariadb://10.178.230.98:3306/hotspot_store
    username: admin
    password: EvzdKZX1XR
logging:
  level:
    root: INFO
redis:
  uri: redis://O6L6ATk7Be@10.178.230.75:6379

--- # local
spring:
  profiles: local
  application:
    basePath: /swagger-ui.html
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/depd
    username: root
    password: root
logging:
  level:
    root: DEBUG
redis:
  uri: redis://localhost:6379/

