apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
    version: version-0.1
    stage: dev
    rel: beta
    owner: dex-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: dep-dev-registry.cloudzcp.io/hot-spot/store:0.1
      imagePullSecrets:
        - name: jonas-secret