apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotspot-store
    version: version-0.1
    stage: dev
    rel: beta
    owner: dex-dev
  name: hotspot-store
  #namespace: dex-dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hotspot-store